name: 1.0$(rev:.r) # build numbering format

variables:
  BuildConfiguration: 'Release'
  SolutionName: 'MLVSH.Testing.sln'
  WorkingDirectory: '$(Build.ArtifactStagingDirectory)/Dist'
  
resources:
  repositories:
  - repository: ALMStuff
    type: github
    name: DrMueller/ALMStuff
    ref: refs/heads/master
    endpoint: GitHub-DrMueller

jobs:
- job: 'BuildAndPublishToNuGet'
  displayName: 'Build and publish Visual Studio Solution'
  pool:
    name: Azure Pipelines
    vmImage: windows-2019

  steps:
  - template: AzureDevOps/BuildTemplates/NetFramework/Steps/Initialize_And_Test.yaml@ALMStuff
    parameters:
      BuildConfiguration: $(BuildConfiguration)
      SolutionName: $(SolutionName)
      BuildOutputPath: $(WorkingDirectory)
  - template: AzureDevOps/BuildTemplates/NetFramework/Steps/Publish_To_Marketplace.yaml@ALMStuff
    parameters:
      ManifestJsonPath: 'Sources/Application/extension-manifest.json'
      WorkingDirectory: $(WorkingDirectory)